name: Build APK

on: release

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build code
        run: ./gradlew build
      - name: Publish package
        run: ./gradlew publish
        env:
         TOKEN: ${{ secrets.TOKEN }}
         USERNAME: "Raphdf201"
