name: Publish to gh Packages

on: release

jobs:
  Gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build code
        run: ./gradlew build
      - name: Publish package
        run: ./gradlew publish
